!dataclass:Config
# checkpoint and eval
eval_freq: 10
eval_num_steps: 2
save_checkpoint: false
restore: "scratch"  # scratch | pre-trained | gpt
checkpoint_dir: "checkpoints"
log_freq: 1
wandb: false
wandb_project_name: "flash-nano-gpt"
wandb_run_id: "test-gpt"
# data
dataset_dir: "data/shakespeare"
vocab_size: 50304
grad_accum_steps: 1
batch_size: 32
block_size: 32
buffer_size: 5
prefetch: 2
# model
num_layers: 8
num_heads: 4
embd_dim: 128
dropout_rate: 0.0
use_bias: false
# Optimizer
num_iters: 1000
lr: 0.0006
lr_decay: true
lr_warmup_iters: 200
lr_decay_iters: 1000
lr_min: 0.00006
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0
# training
seed: 0
amp: false
skip_infinite: true
jit: false